name: Automation
on:
    push:
      branches: [ '**' ]
      tags: [ '**' ]
    release:
      types: [ published ]
    pull_request:
      branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run:  xvfb-run --auto-servernum npm test
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
